version: '3.1'
services:
  ihm:
    image: php:apache 
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
    - USERNAME=toto
    - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    networks:
      - ulrich-networks
  
  api:
    image: student-age:v1
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - "8500:5000"
    container_name: api-student
    networks:
      - ulrich-networks

networks:
  ulrich-networks: